# Generated by Django 4.0.4 on 2022-04-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tracks',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
