# Generated by Django 4.0.4 on 2022-04-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0004_rename_age_student_count_remove_student_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
