# Generated by Django 4.0.4 on 2022-04-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0006_rename_student_usermanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
