# Generated by Django 4.0.4 on 2022-04-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0007_usermanagement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='Time',
            field=models.DateTimeField(),
        ),
    ]
