# Generated by Django 4.0.4 on 2022-04-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0008_alter_usermanagement_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanagement',
            old_name='Time',
            new_name='time',
        ),
    ]
