# Generated by Django 4.0.4 on 2022-04-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0009_rename_time_usermanagement_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='date_enrolled',
        ),
    ]
