# Generated by Django 4.0.4 on 2022-04-18 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0010_remove_usermanagement_date_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='time',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
