# Generated by Django 4.0.4 on 2022-04-18 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0011_remove_usermanagement_time_usermanagement_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
