# Generated by Django 4.0.4 on 2022-04-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0012_alter_usermanagement_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='start_time',
        ),
    ]
