# Generated by Django 4.0.4 on 2022-04-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0013_remove_usermanagement_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanagement',
            old_name='count',
            new_name='credit',
        ),
    ]
