# Generated by Django 4.0.4 on 2022-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0014_rename_count_usermanagement_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='credit_limit',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
