# Generated by Django 4.0.4 on 2022-04-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0016_imageinferproto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinferproto',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
