# Generated by Django 4.0.4 on 2022-04-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0020_alter_imageinferproto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinferproto',
            name='name',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
