# Generated by Django 4.0.4 on 2022-04-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0023_remove_usermanagement_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanagement',
            old_name='updated_on',
            new_name='lastest_call',
        ),
    ]
