# Generated by Django 4.0.4 on 2022-05-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0024_rename_updated_on_usermanagement_lastest_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yolov5Proto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.BinaryField()),
                ('results', models.CharField(max_length=10000)),
            ],
        ),
    ]
