# Generated by Django 4.0.4 on 2022-05-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0025_yolov5proto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlprProto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mode', models.IntegerField()),
                ('country', models.CharField(max_length=10)),
                ('image', models.BinaryField()),
                ('results', models.CharField(max_length=10000)),
            ],
        ),
    ]
