# Generated by Django 4.0.4 on 2022-05-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0028_alter_alprproto_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alprproto',
            name='mode',
            field=models.IntegerField(),
        ),
    ]
