# Generated by Django 4.0.4 on 2022-05-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0029_alter_alprproto_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alprproto',
            name='image',
            field=models.CharField(max_length=10000),
        ),
    ]
