# Generated by Django 4.0.4 on 2022-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiApp', '0030_alter_alprproto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alprproto',
            name='image',
            field=models.BinaryField(),
        ),
    ]
